#include <iostream>
#include <iomanip>


  using namespace std;
  int main() {
  	
  	cout<<"Enter the window style for the FAST Main Building: ";
  	char a;
  	cin>>a;
  	
  	cout<<"Enter the grass style for the FAST Main Building: ";
  	char b;
  	cin>>b;
  	
  	
	cout<<setfill(' ')<<setw(9)<<(' ')<<setfill('!')<<setw(1)<<('!')<<setfill(' ')<<setw(32)<<(' ')<<setfill('@')<<setw(1)<<('@')<<setfill(' ')<<setw(31)<<(' ')<<setfill('!')<<setw(1)<<('!')<<endl
	
	<<setfill(' ')<<setw(8)<<(' ')<<setfill('(')<<setw(1)<<('(')<<setfill('*')<<setw(1)<<('*')<<setfill(')')<<setw(1)<<(')')<<setfill(' ')<<setw(29)<<(' ')<<setfill('(')<<setw(1)<<('(')<<setfill('*')<<setw(3)<<('*')<<setfill(')')<<setw(1)<<(')')<<setfill(' ')<<setw(28)<<(' ')<<setfill('(')<<setw(1)<<('(')<<setfill('*')<<setw(1)<<('*')<<setfill(')')<<setw(1)<<(')')<<endl
	
	<<setfill(' ')<<setw(7)<<(' ')<<setfill('(')<<setw(1)<<('(')<<setfill('*')<<setw(3)<<('*')<<setfill(')')<<setw(1)<<(')')<<setfill(' ')<<setw(26)<<(' ')<<setfill('(')<<setw(2)<<('(')<<setfill('*')<<setw(5)<<('*')<<setfill(')')<<setw(2)<<(')')<<setfill(' ')<<setw(25)<<(' ')<<setfill('(')<<setw(1)<<('(')<<setfill('*')<<setw(3)<<('*')<<setfill(')')<<setw(1)<<(')')<<endl
	
	<<setfill(' ')<<setw(6)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill('#')<<setw(1)<<('#')<<setfill('|')<<setw(1)<<('|')<<setfill('#')<<setw(1)<<('#')<<setfill('|')<<setw(1)<<('|')<<setfill('#')<<setw(1)<<('#')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(24)<<(' ')<<setfill('(')<<setw(2)<<('(')<<setfill('|')<<setw(1)<<('|')<<setfill('#')<<setw(1)<<('#')<<setfill('|')<<setw(1)<<('|')<<setfill('#')<<setw(1)<<('#')<<setfill('|')<<setw(1)<<('|')<<setfill('#')<<setw(1)<<('#')<<setfill('|')<<setw(1)<<('|')<<setfill(')')<<setw(2)<<(')')<<setfill(' ')<<setw(23)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill('#')<<setw(1)<<('#')<<setfill('|')<<setw(1)<<('|')<<setfill('#')<<setw(1)<<('#')<<setfill('|')<<setw(1)<<('|')<<setfill('#')<<setw(1)<<('#')<<setfill('|')<<setw(1)<<('|')<<endl
	
	<<setfill(' ')<<setw(3)<<(' ')<<setfill('/')<<setw(1)<<('/')<<setfill('\\')<<setw(1)<<('\\')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('*')<<setw(5)<<('*')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('#')<<setw(11)<<('#')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('*')<<setw(5)<<('*')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill('/')<<setw(1)<<('/')<<setfill('\\')<<setw(1)<<('\\')<<endl
	
	<<setfill(' ')<<setw(3)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(3)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(3)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(1)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(1)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(1)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<endl
	
	<<setfill(' ')<<setw(3)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<setfill('=')<<setw(1)<<('=')<<setfill(' ')<<setw(1)<<(' ')<<endl
	
	<<setfill(' ')<<setw(3)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(4)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(1)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(1)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(1)<<(' ')<<setfill(' ')<<setw(1)<<(' ')<<setfill(' ')<<setw(1)<<(' ')<<setfill(' ')<<setw(1)<<(' ')<<setfill(' ')<<setw(1)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(1)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(1)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(3)<<(' ')<<setfill('|')<<setw(1)<<('|')<<endl

	<<setfill(' ')<<setw(3)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(4)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(1)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(1)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(1)<<(' ')<<setfill(' ')<<setw(1)<<(' ')<<setfill(' ')<<setw(1)<<(' ')<<setfill(' ')<<setw(1)<<(' ')<<setfill(' ')<<setw(1)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(1)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(1)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(3)<<(' ')<<setfill('|')<<setw(1)<<('|')<<endl

	<<setfill(' ')<<setw(3)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(4)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(1)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill('_')<<setw(1)<<('_')<<setfill('|')<<setw(1)<<('|')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill('|')<<setw(1)<<('|')<<setfill('_')<<setw(1)<<('_')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(1)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(3)<<(' ')<<setfill('|')<<setw(1)<<('|')<<endl

	<<setfill(' ')<<setw(3)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(4)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(1)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(1)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(1)<<(' ')<<setfill(' ')<<setw(1)<<(' ')<<setfill(' ')<<setw(1)<<(' ')<<setfill(' ')<<setw(1)<<(' ')<<setfill(' ')<<setw(1)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(1)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(1)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(3)<<(' ')<<setfill('|')<<setw(1)<<('|')<<endl

	<<setfill(' ')<<setw(3)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(4)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(1)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill('_')<<setw(1)<<('_')<<setfill('|')<<setw(1)<<('|')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill('|')<<setw(1)<<('|')<<setfill('_')<<setw(1)<<('_')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(1)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill(a)<<setw(1)<<(a)<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(2)<<(' ')<<setfill('|')<<setw(1)<<('|')<<setfill(' ')<<setw(3)<<(' ')<<setfill('|')<<setw(1)<<('|')<<endl

	<<setfill(' ')<<setw(2)<<(' ')<<setfill('/')<<setw(1)<<('/')<<setfill(' ')<<setw(33)<<(' ')<<setfill('/')<<setw(1)<<('/')<<setfill(' ')<<setw(4)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(4)<<(' ')<<setfill('\\')<<setw(1)<<('\\')<<setfill(' ')<<setw(31)<<(' ')<<setfill('\\')<<setw(1)<<('\\')<<setfill(' ')<<setw(2)<<(' ')<<endl

	<<setfill(' ')<<setw(1)<<(' ')<<setfill('/')<<setw(1)<<('/')<<setfill(' ')<<setw(4)<<(' ')<<setfill(b)<<setw(1)<<(b)<<setfill(' ')<<setw(2)<<(' ')<<setfill(b)<<setw(1)<<(b)<<setfill(' ')<<setw(2)<<(' ')<<setfill(b)<<setw(1)<<(b)<<setfill(' ')<<setw(2)<<(' ')<<setfill(b)<<setw(1)<<(b)<<setfill(' ')<<setw(2)<<(' ')<<setfill(b)<<setw(1)<<(b)<<setfill(' ')<<setw(2)<<(' ')<<setfill(b)<<setw(1)<<(b)<<setfill(' ')<<setw(2)<<(' ')<<setfill(b)<<setw(1)<<(b)<<setfill(' ')<<setw(2)<<(' ')<<setfill(b)<<setw(1)<<(b)<<setfill(' ')<<setw(1)<<(' ')<<setfill(' ')<<setw(6)<<(' ')<<setfill('/')<<setw(1)<<('/')<<setfill(' ')<<setw(4)<<(' ')<<setfill('/')<<setw(1)<<('/')<<setfill('_')<<setw(1)<<('_')<<setfill(' ')<<setw(1)<<(' ')<<setfill('_')<<setw(1)<<('_')<<setfill('\\')<<setw(1)<<('\\')<<setfill(' ')<<setw(4)<<(' ')<<setfill('\\')<<setw(1)<<('\\')<<setfill(' ')<<setw(4)<<(' ')<<setfill(b)<<setw(1)<<(b)<<setfill(' ')<<setw(2)<<(' ')<<setfill(b)<<setw(1)<<(b)<<setfill(' ')<<setw(2)<<(' ')<<setfill(b)<<setw(1)<<(b)<<setfill(' ')<<setw(2)<<(' ')<<setfill(b)<<setw(1)<<(b)<<setfill(' ')<<setw(2)<<(' ')<<setfill(b)<<setw(1)<<(b)<<setfill(' ')<<setw(2)<<(' ')<<setfill(b)<<setw(1)<<(b)<<setfill(' ')<<setw(2)<<(' ')<<setfill(b)<<setw(1)<<(b)<<setfill(' ')<<setw(2)<<(' ')<<setfill(b)<<setw(1)<<(b)<<setfill(' ')<<setw(1)<<(' ')<<setfill(' ')<<setw(4)<<(' ')<<setfill('\\')<<setw(1)<<('\\')<<setfill(' ')<<setw(1)<<(' ')<<endl;




  return 0;
}


 
 
